#!/usr/bin/env bash

# Forward stderr to stdout for use with runit svlogd
exec 2>&1

# Make sure syslog is running before we start
sv start syslog-ng || exit
sleep 2

PIDFILE=/var/run/haproxy.pid
CONFIG=/etc/haproxy/config/haproxy.cfg
HAPROXY=/usr/sbin/haproxy
RUNDIR=/run/haproxy
EXTRAOPTS=

# Just give up if the binary isn't here
test -x $HAPROXY || Exit 0

# Load up any default settings
if [ -e /etc/default/haproxy ]; then
	. /etc/default/haproxy
fi

# Make sure the config file exists
test -f "$CONFIG" || exit 0

# Assert correct permissions on run directory
[ -d "$RUNDIR" ] || mkdir "$RUNDIR"
chown haproxy:haproxy "$RUNDIR"
chmod 2775 "$RUNDIR"

# Check syntax of configuration
$HAPROXY -c -f "$CONFIG" >/dev/null
if [ $? -eq 1 ]; then
    log_end_msg 1
    exit 1
fi

exec /bin/bash <<EOF
    $HAPROXY -f $CONFIG -D -p $PIDFILE
    
    trap "echo SIGHUP caught; $HAPROXY -f $CONFIG -D -p $PIDFILE -sf \\\$(cat $PIDFILE)" SIGHUP
    trap "echo SIGTERM caught; kill -TERM \\\$(cat $PIDFILE) && exit 0" SIGTERM SIGINT
    
    while true; do # Iterate to keep job running.
      sleep 1 # Wake up to handle signals
    done
EOF